name: sysfoo-ci
on:
  push:
    branches:
      - 'master'
jobs:
  sysfoo-ci-job:
    runs-on: ubuntu-latest
    steps:
      - name: sysfoo-ci-name
        run: echo "Welcome to Sysfoo Application"
        
      - name: code checkout
        uses: actions/checkout@v6
        
      - name: Test
        run: mvn test
        
      - name: Clean Package
        run: mvn clean
        
      - name: Install Package
        run: mvn package

      - name: View the files
        run: ls -lrt target

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sysfoo Artifact
          path: target/**.war
        

        
